-- 1º ADS A - ATIVIDADE EM GRUPO 23/08/2024

CREATE DATABASE OLIMPIADAS; -- CRIA UM BANCO

USE OLIMPIADAS; -- SELECIONA O BANCO QUE SERÁ USADO

Create Table Atletas(
	idAtletas int primary key auto_increment, 
    NOME VARCHAR(40),
    MODALIDADE VARCHAR(40),
    PAÍS VARCHAR(60)
    ); -- CRIA UMA TABELA

Desc atletas; -- DESC OU DESCRIBE - DESCREVE A ESTRUTURA DE UMA TABELA

INSERT INTO ATLETAS VALUES(default, 'Lucas Aiello', 'basquete', 'Brasil'); -- COM O AUTO_INCREMENT O DEFAUT NÃO É NECESSÁRIO. 
	-- A LINHA ACIMA PODERIA SER ESCCRITA DA SEGUINTE FORMA: INSERT INTO ATLETAS (NOME, MODALIDADE, PAÍS) VALUES ('LUCAS AIELLO', 'BASQUETE', 'BRASIL') PARA EVITAR REDUNDÂNCIAS;
	-- ESPECIFICAR UM VALOR DEFAULT PARA UMA COLUNA QUE JÁ SE AUTOINCREMENTA É REDUNDANTE, POIS O VALOR SERÁ SOBRESCRITO PELO MECANISMO DE AUTOINCREMENTO.


INSERT INTO ATLETAS VALUES (default, 'Marcos', 'Natação', 'Brasil'); -- INSERE DADOS NA TABELA, DESDE QUE A LINHA NÃO EXISTA

SELECT * FROM Atletas; -- CONSULTA/MOSTRA OS DADOS DA TABELA

SELECT NOME FROM Atletas WHERE NOME = 'lucas Aiello'; -- CONSULTA OS DADOS DE UMA TABELA ONDE ATENDA UMA CONDIÇÃO EXPECÍFICA

SELECT * FROM Atletas
	WHERE NOME LIKE 'M%';
    
Select País from Atletas Where País like '%i_';

SELECT MODALIDADE FROM ATLETAS WHERE MODALIDADE LIKE '%A%';

Alter table Atletas add column qtdMedalhas  int; -- ADICIONA MAIS UMA COLUNA À TABELA

UPDATE ATLETAS SET qTDMEDALHAS = 2 WHERE IDATLETAS = 1; -- ALTERA/ADIONA VALORES DE UMA LINHA JÁ EXISTENTE

UPDATE ATLETAS SET QTDMEDALHAS = 5 WHERE IDATLETAS = 2;

ALTER TABLE ATLETAS DROP COLUMN PAÍS; -- APAGA UMA COLUNA

INSERT INTO ATLETAS VALUES
	(DEFAULT, 'Rebeca Andrade', 'ginastica', 5);
    
ALTER TABLE ATLETAS MODIFY COLUMN NOME VARCHAR(100); -- MODIFICA A ESTRUTURA DE UMA COLUNA, NESTE CASO ELE MODIFICA A TIPAGEM

alter table atletas rename column NOME to atleta; -- ALTERA O NOME DA COLUNA

Delete from Atletas where idAtletas = 2; -- DELETA UMA LINHA DA COLUNA

-- TRUNCATE TABLE ATLETAS; -- APAGA APENAS OS DADOS DA TABELA

-- DROP TABLE ATLETAS; -- APAGA A TABELA INTEIRA (DADOS E ESTRUTURA)

-- OBSERVAÇÕES:
	-- NÃO É UMA BOA PRÁTICA COLOCAR O NOME DE TABELAS NO PRURAL, MAS SIM NO SINGULAR
    -- 	USAR '' AO INVÉS DE ""
	-- NOT NULL INDICA QUE OS DADOS DE UMA COLUNA NÃO PODEm SER NULOs
	-- O SQL NÃO É CASE SENSITIVE, NÃO IMPORTA SE SERÁ USADO LETRAS EM MÍNUSCULO, MAIUSCULA OU UMA JUNÇÃO DAS DUAS, O PROGRAMA FUNCIONARÁ DA MESMA FORMA
    -- NUNCA ESQUECER DAS VIRGULAS E PONTOS E VIRGULAS;
    -- OU SE USA "LIKE" OU SE USA "=", NUNCA OS DOIS JUNTOS.
		-- "=" SIGNIFICA "IDÊNTICO/IGUAL" E "LIKE" SIGNIFICA "PARECIDO", LOGO UMA COISA NÃO PODE SER IDENTICA E PARECIDA AO MESMO TEMPO

-- TIPOS DE COMANDOS
	-- D(D)L - COMANDOS QUE DEFINEM DADOS (DATA DEFINITION LANGUAGE)
	-- D(M)L - COMANDOS QUE MANIPULAM DADOS (DATA MANIPULATION LANGUAGE)
	-- D(Q)L - COMANDOS DE CONSULTAS (DATA QUERY LANGUAGE)
		-- * SELECT É TANTO UM COMANDO D(M)L QUANTO D(Q)L
	-- D(C)L - COMANDOS DE CONTROLE DE ACESSO (DATA CONTROL LANGUAGE)


  