-- ISSO É UM COMENTÁRIO
-- TODO  COMANDO TERMINA COM ";"

-- CRIAR UM BANCO DE DADOS
CREATE DATABASE adsa;

-- SELECIONAR O BANCO DE DADOS
USE adsa;

-- CRIAR TABELA
CREATE TABLE aluno (
-- TODA TABELA TEM UM PRIMARY KEY
ra char(8) primary key,
nome varchar(50),
email varchar(30)
);

-- DESCREVER OS CAMPOS DA TABELA
DESCRIBE aluno;
DESC aluno;

-- INSERIR DADOS
INSERT INTO aluno VALUES ('01242031', 'Beatriz', 'bia@sptech.school');

-- EXIBIR OS DADOS DA ALUNA
SELECT ra, nome, email FROM aluno; -- MOSTRA CAMPOS ESPECÍFICOS
SELECT ra FROM aluno; -- MOSTRA UM CAMPO ESPECÍFICO
SELECT * FROM aluno; -- MOSTRA TODOS OS CAMPOS

INSERT INTO aluno VALUES 
('01242115', 'Rennan', 'rennan@sptech.school'),
('01242045', 'Daniel', 'daniel@sptech.school');

SELECT * FROM aluno;

-- EXIBIR APENAS O ALUNO CUJO NOME É BEATRIZ
SELECT nome FROM aluno WHERE nome = 'Beatriz'; -- CONDIÇÃO

-- EXIBIR O ALUNO CUJO NOME COMEÇA COM "R"
SELECT nome FROM aluno WHERE nome LIKE 'R%';

-- EXIBIR O ALUNO CUJO NOME QUE TERMINA COM "N"
SELECT nome FROM aluno WHERE nome LIKE '%N';

-- EXIBIR O ALUNO CUJA A SEGUNDA TERCEIRA LETRA É "N"
SELECT nome FROM aluno WHERE nome LIKE '__N%';

-- EXIBIR O ALUNO QUE CONTEM A LETRA "A"
SELECT nome FROM aluno WHERE nome LIKE '%A%';

-- EXIBIR OS ALUNOS QUE É DIFERENTE DE "RENNAN"
SELECT nome FROM aluno WHERE nome != 'RENNAN';
SELECT nome FROM aluno WHERE nome <> 'RENNAN';

-- EXIBIR OS ALUNO EM ORDEM ALFABÉTICA
SELECT * FROM aluno ORDER BY nome;

-- EXIBIR OS ALUNO EM ORDEM DECRESCENTE ALFABÉTICA
SELECT * FROM aluno ORDER BY nome DESC;
